/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cmpt383_project_cfiles_HelloJNI */

#ifndef _Included_com_cmpt383_project_cfiles_HelloJNI
#define _Included_com_cmpt383_project_cfiles_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cmpt383_project_cfiles_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_cmpt383_project_cfiles_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
